language: python
python:
  - 3.9
services:
  postgresql
addons:
  postgresql: '13.2'
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv install codecov
  - pipenv sync --dev
  - cp contrib/env-sample .env
before_script:
  - psql -c "CREATE DATABASE testedb;" -U postgres
script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro
after_success:
  - pipenv run codecov